In [1]:
import pandas as pd
train = pd.read_csv('./train.csv', encoding='ISO-8859-1')
train = train.dropna()

## Data Preprocessing

In [2]:
# Get the Independent Features
X = train.drop('Label', axis=1)
X = X.drop('Date', axis=1)

In [3]:
# Get the Dependent features
y = train['Label']

In [4]:
X.head()

Top1  \
0  b"Georgia 'downs two Russian warplanes' as cou...   
1  b'Why wont America and Nato help us? If they w...   
2  b'Remember that adorable 9-year-old who sang a...   
3  b' U.S. refuses Israel weapons to attack Iran:...   
4  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  \
0  b"The 'enemy combatent' trials are nothing but...   
1  b'An American citizen living in S.Ossetia blam...   
2  b"I'm Trying to Get a Sense of This Whole Geor...   
3             b'Russian forces sink Georgian ships '   
4  b'Will the Russians conquer Tblisi? Bet on it,...   

                                                Top9  \
0  b'Georgian troops retreat from S. Osettain cap...   
1  b'Welcome To World War IV! Now In High Definit...   
2  b"The US military was surprised by the timing ...   
3  b"The commander of a Navy air reconnaissance s...   
4  b'Russia exaggerating South Ossetian death tol...   

                                               Top10  ...  \
0  b'Did the U.S. Prep Georgia for War with Russia?'  ...   
1  b"Georgia's move, a mistake of monumental prop...  ...   
2    b'U.S. Beats War Drum as Iran Dumps the Dollar'  ...   
3  b"92% of CNN readers: Russia's actions in Geor...  ...   
4  b' Musharraf expected to resign rather than fa...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set 

In [5]:
X.shape

(1986, 25)

In [6]:
y.shape

(1986,)

In [7]:
new_Index = [str(i) for i in range(25)]
X.columns = new_Index

In [8]:
messages = X.copy().reset_index()
messages = messages.drop('index', axis=1)
messages.head()

0  \
0  b"Georgia 'downs two Russian warplanes' as cou...   
1  b'Why wont America and Nato help us? If they w...   
2  b'Remember that adorable 9-year-old who sang a...   
3  b' U.S. refuses Israel weapons to attack Iran:...   
4  b'All the experts admit that we should legalis...   

                                                   1  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                   2  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                   3  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                   4  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                   5  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                   6  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                   7  \
0  b"The 'enemy combatent' trials are nothing but...   
1  b'An American citizen living in S.Ossetia blam...   
2  b"I'm Trying to Get a Sense of This Whole Geor...   
3             b'Russian forces sink Georgian ships '   
4  b'Will the Russians conquer Tblisi? Bet on it,...   

                                                   8  \
0  b'Georgian troops retreat from S. Osettain cap...   
1  b'Welcome To World War IV! Now In High Definit...   
2  b"The US military was surprised by the timing ...   
3  b"The commander of a Navy air reconnaissance s...   
4  b'Russia exaggerating South Ossetian death tol...   

                                                   9  ...  \
0  b'Did the U.S. Prep Georgia for War with Russia?'  ...   
1  b"Georgia's move, a mistake of monumental prop...  ...   
2    b'U.S. Beats War Drum as Iran Dumps the Dollar'  ...   
3  b"92% of CNN readers: Russia's actions in Geor...  ...   
4  b' Musharraf expected to resign rather than fa...  ...   

                                                  15  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                                  16  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set bac

In [9]:
import nltk
import re
from nltk.corpus import stopwords

In [10]:
# Text Preprocessing - removal of non-english characters, tokeization, and stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    words = str(messages.iloc[i])
    review = re.sub('b[\'\"]', '', words)
    review = re.sub('Name: ., dtype: object', '', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['georgia down two russian warplan cou break musharraf impeach russia today column troop roll russian tank move toward capit afghan children rape impun u n russian tank enter south ossetia break georgia invad south ossetia ru enemi combat trial noth georgian troop retreat osettain cap u prep georgia war russia rice give green light israel attack announc class action lawsuit behalf russia georgia war n china tell bush stay countr world war iii start today georgia invad south ossetia russia ge al qaeda face islamist backlash condoleezza rice us would act p busi day european union georgia withdraw soldier ir pentagon think attack iran caucasu crisi georgia invad south os indian shoe manufactori se visitor suffer mental ill ban help mexico kidnap surg',
 'wont america nato help us w bush put foot georgian conflict jewish georgian minist thank isra georgian armi flee disarray russian olymp open ceremoni firework fake mossad fraudul new zea russia anger isra militari sale g american citizen 

### Onehot Representation

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
maximum=0
for sent in corpus:
    maximum=max(maximum, len(sent.split()))
maximum

158

In [14]:
# Hyper parameters
voc_size = 10000
embedding_vector_features = 128
sent_length = 100

In [15]:
onehot_repr = [one_hot(words,voc_size) for words in corpus] 
onehot_repr

[[601,
  6908,
  3161,
  8116,
  4437,
  1339,
  8064,
  2237,
  342,
  2384,
  4594,
  6609,
  9327,
  8989,
  8116,
  7637,
  553,
  8878,
  2957,
  4346,
  1379,
  7795,
  6900,
  4935,
  8442,
  8116,
  7637,
  958,
  3538,
  5029,
  8064,
  601,
  8323,
  3538,
  5029,
  6922,
  3890,
  6349,
  3897,
  3579,
  3147,
  9327,
  2542,
  9641,
  2287,
  4935,
  6681,
  601,
  7505,
  2384,
  7155,
  2191,
  589,
  9520,
  2628,
  4251,
  3319,
  6077,
  983,
  2693,
  7530,
  2384,
  601,
  7505,
  8442,
  31,
  224,
  2646,
  8515,
  7158,
  776,
  7505,
  9071,
  6369,
  4594,
  601,
  8323,
  3538,
  5029,
  2384,
  6523,
  2794,
  3533,
  8428,
  7770,
  7909,
  7712,
  7155,
  559,
  4277,
  8001,
  267,
  5960,
  3160,
  6982,
  2259,
  601,
  3795,
  2184,
  1138,
  8680,
  8210,
  4251,
  2760,
  5824,
  8755,
  601,
  8323,
  3538,
  8081,
  4272,
  6671,
  3303,
  549,
  8782,
  4244,
  1661,
  4125,
  6743,
  177,
  2697,
  2845,
  6613],
 [5267,
  3340,
  2167,
  177,
  55

### Embedding Representation

In [16]:
embedded_docs = pad_sequences(onehot_repr, padding='post', maxlen=sent_length)
print(embedded_docs)
print(sent_length)

[[4935 8442 8116 ... 2697 2845 6613]
 [2212 2799 1681 ... 3511 7043 6607]
 [ 783  601   70 ... 4044 3454 6345]
 ...
 [9596 3483 9842 ... 8523 3207 2454]
 [4346 5662 1784 ... 8523 3207 2454]
 [5087 9736 9067 ... 8523 3207 2454]]
100


In [17]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [18]:
X_final.shape, y_final.shape

((1986, 100), (1986,))

## Creating and Training Model

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

In [20]:
## Creating model
model=Sequential()
model.add(Embedding(input_dim = voc_size, output_dim = embedding_vector_features, input_length=sent_length))
model.add(LSTM(16))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

### Splitting the Dataset

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, shuffle=False)
X_train.shape, X_test.shape

((1588, 100), (398, 100))

### Model Training

In [22]:
# Finally Training
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, batch_size=8,
          callbacks=EarlyStopping(patience=5, start_from_epoch=10, restore_best_weights=True))

Epoch 1/20


199/199 [==============================] - 15s 50ms/step - loss: 0.6913 - accuracy: 0.5384 - val_loss: 0.6969 - val_accuracy: 0.5075
Epoch 2/20
199/199 [==============================] - 9s 44ms/step - loss: 0.5697 - accuracy: 0.7047 - val_loss: 0.8207 - val_accuracy: 0.4950
Epoch 3/20
199/199 [==============================] - 9s 44ms/step - loss: 0.1785 - accuracy: 0.9440 - val_loss: 1.2667 - val_accuracy: 0.5000
Epoch 4/20
199/199 [==============================] - 9s 45ms/step - loss: 0.0336 - accuracy: 0.9937 - val_loss: 1.8322 - val_accuracy: 0.5151
Epoch 5/20
199/199 [==============================] - 9s 44ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 2.1278 - val_accuracy: 0.5151
Epoch 6/20
199/199 [==============================] - 9s 44ms/step - loss: 0.0024 - accuracy: 1.0000 - val_loss: 2.3053 - val_accuracy: 0.5251
Epoch 7/20
199/199 [==============================] - 9s 45ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 2.4421 - val_accuracy: 0.5

## Prediction, Performance Metrics And Accuracy

In [23]:
prediction = model.predict(X_test)
prediction

13/13 [==============================] - 1s 13ms/step


array([[1.3651161e-01],
       [2.5604209e-02],
       [3.9522693e-02],
       [9.9936122e-01],
       [9.9927747e-01],
       [9.7325540e-01],
       [9.9933755e-01],
       [4.6600532e-04],
       [9.9948937e-01],
       [9.9900240e-01],
       [4.1168329e-01],
       [9.8900056e-01],
       [4.4029020e-03],
       [9.9354857e-01],
       [9.9898875e-01],
       [1.1073280e-03],
       [9.9955159e-01],
       [9.9921340e-01],
       [6.1355787e-04],
       [9.8579454e-01],
       [7.7544642e-04],
       [8.7933132e-04],
       [9.9952060e-01],
       [9.0881163e-01],
       [3.7518407e-03],
       [2.5276479e-03],
       [3.6086768e-02],
       [2.8284760e-03],
       [4.1748551e-03],
       [2.0451243e-03],
       [9.4977492e-01],
       [4.0583061e-03],
       [9.9949276e-01],
       [9.0284890e-01],
       [5.9459609e-04],
       [9.9884075e-01],
       [9.9868083e-01],
       [7.0770201e-04],
       [9.9948347e-01],
       [8.6157850e-04],
       [9.9924046e-01],
       [1.126858

In [24]:
# rounding up all the results because the metrics need whole numbers
y_pred=[]
for pred in prediction:
    y_pred.append(round(pred[0]))

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [26]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)
score = accuracy_score(y_test, y_pred)
print(score)
report = classification_report(y_test, y_pred)
print(report)

[[ 87 109]
 [ 82 120]]
0.5201005025125628
              precision    recall  f1-score   support

           0       0.51      0.44      0.48       196
           1       0.52      0.59      0.56       202

    accuracy                           0.52       398
   macro avg       0.52      0.52      0.52       398
weighted avg       0.52      0.52      0.52       398

